//
//  Structure.Filter+static.swift
//  Hippocampus
//
//  Created by Guido Kühn on 19.06.24.
//  Generated by Hippocampus on 22.07.2024 01:26.
//

import Foundation
import SwiftUI
import Grisu

extension Structure.Filter {
    typealias Filter = Structure.Filter
    typealias Aspect = Structure.Aspect
    typealias Particle = Structure.Particle

	static var statics: [Filter] = [.filter1, .filter2]


static let filter1: Filter = {
	var filter = Filter(id: "46200247-E337-490A-96C0-DBF236EF9C2A".uuid)
	filter.name = "Filter 1"
	filter.layouts = [.tree,.list]
	filter.roles = [.topic, .note]
	filter.superFilters = [.group2]
	filter.condition = .role(Structure.Role.tracked.id)
	return filter
}()


static let filter2: Filter = {
	var filter = Filter(id: "25B650F4-D5E9-46A0-B11E-E760F547014D".uuid)
	filter.name = "Filter 2"
	filter.layouts = [.tree,.list]
	filter.roles = [.topic, .note]
	filter.superFilters = [.group1]
	filter.condition = .role(Structure.Role.tracked.id)
	return filter
}()

}