//
//  Structure.Filter+static.swift
//  Hippocampus
//
//  Created by Guido Kühn on 19.06.24.
//  Generated by Hippocampus on 03.08.2024 14:33.
//

import Foundation
import SwiftUI
import Grisu

extension Structure.Filter {
	typealias Filter = Structure.Filter
	typealias Aspect = Structure.Aspect
	typealias Particle = Structure.Particle

	static var statics: [Filter] { [Statics.malSehen, Statics.test] }

	enum Statics {
			static var malSehen: Filter {
				let filter = Filter(id: "B9BFBC68-44ED-4F3E-8F80-5A20F78E7EC5".uuid)
				filter.name = "Mal sehen"
				filter.roles = [Structure.Role.Statics.note]
				
				filter.layouts = [.list, .tree]
				filter.layout = .list
				filter.condition = .hasValue(.equal("6247260E-624C-48A1-985C-CDEDDFA5D3AD".uuid, .init("/Ha/")!))
				filter.orders = [
					.sorted("6247260E-624C-48A1-985C-CDEDDFA5D3AD".uuid, ascending: true)]
				filter.orderIndex = 0
				return filter
			}

			static var test: Filter {
				let filter = Filter(id: "6FD00BE8-2B48-47E7-9EBB-C86F65C3AA7A".uuid)
				filter.name = "Test"
				filter.roles = [Structure.Role.Statics.note, Structure.Role.Statics.topic]
				
				filter.layouts = [.list, .tree]
				filter.layout = .tree
				filter.condition = .role("D7812874-085B-4161-9ABB-C82D4A145634".uuid)
				filter.orders = [
					.sorted("6247260E-624C-48A1-985C-CDEDDFA5D3AD".uuid, ascending: true), 
					.sorted("6247260E-624C-48A1-985C-CDEDDFA5D3AD".uuid, ascending: false)]
				filter.orderIndex = 0
				filter.representations = [
					{
						let representation = Representation()
						representation.condition = .role("8A81358C-2A7C-497D-A93D-306F776C217C".uuid)
						representation.presentation = .vertical([
								.horizontal([
									.color([
										.icon("star.fill")
									], color: Color(hex: "F71DC9"))
								], alignment: .center), 
								.role("8A81358C-2A7C-497D-A93D-306F776C217C".uuid, layout: .list, name: nil)
							], alignment: .leading)
						return representation
					}()
					]
				return filter
			}
	}
}
