//
//  Structure.Filter+static.swift
//  Hippocampus
//
//  Created by Guido Kühn on 19.06.24.
//  Generated by Hippocampus on 22.07.2024 14:58.
//

import Foundation
import SwiftUI
import Grisu

extension Structure.Filter {
    typealias Filter = Structure.Filter
    typealias Aspect = Structure.Aspect
    typealias Particle = Structure.Particle

	static var statics: [Filter] = [.filter1]


static let filter1: Filter = {
	var filter = Filter(id: "08375CA1-A88F-404B-BC24-75C4FCA5754D".uuid)
	filter.name = "Filter 1"
	filter.layouts = [.tree,.list]
	filter.roles = [.topic, .note]
	filter.superFilters = [.group2]
	filter.condition = .role(Structure.Role.tracked.id)
	return filter
}()

}