//
//  Structure.Filter+static.swift
//  Hippocampus
//
//  Created by Guido Kühn on 19.06.24.
//  Generated by Hippocampus on 24.07.2024 02:12.
//

import Foundation
import SwiftUI
import Grisu

extension Structure.Filter {
	typealias Filter = Structure.Filter
	typealias Aspect = Structure.Aspect
	typealias Particle = Structure.Particle

	static var statics: [Filter] = [.test]


	static let test: Filter = {
		var filter = Filter(id: "6FD00BE8-2B48-47E7-9EBB-C86F65C3AA7A".uuid)
		filter.name = "Test"
		filter.roles = [.note, .topic]
		
		filter.layouts = [.list, .tree]
		filter.layout = .tree
		filter.condition = .role(Structure.Role.tracked.id)
		filter.orders = [.sorted("6247260E-624C-48A1-985C-CDEDDFA5D3AD".uuid, ascending: true), .sorted("6247260E-624C-48A1-985C-CDEDDFA5D3AD".uuid, ascending: false)]
		filter.orderIndex = 0
		filter.representations = [
			{
				let representation = Representation()
				representation.condition = .role(Structure.Role.named.id)
				representation.presentation = .vertical([
						.horizontal([
							.color([
								.icon("star.fill")
							], color: Color(hex: "F71DC9"))
						], alignment: .center), 
						.role(Structure.Role.named.id, layout: .list, name: nil)
					], alignment: .leading)
				return representation
			}()
			]
		return filter
	}()

}